# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: senha
  host: localhost

development:
  <<: *default
  database: attentionclass_development

test:
  <<: *default
  database: attentionclass_test

production:
  <<: *default
  database: attentionclass_production
  username: attentionclass
  password: <%= ENV['ATTENTIONCLASS_DATABASE_PASSWORD'] %>
